;;; eglot-inactive-regions-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eglot-inactive-regions.el

(register-definition-prefixes "eglot-inactive-regions" '("eglot-inactive-regions-"))

;;; End of scraped data

(provide 'eglot-inactive-regions-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eglot-inactive-regions-autoloads.el ends here
